# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"


cache:
  directories:
    - $HOME/.cache/pip

# command to install dependencies, e.g. pip install -r requirements.txt
install:
    - pip install -r dev-requirements.txt

# command to run tests, e.g. python setup.py test
script:
    - make lint
    - make test

after_success:
  - make coverage
  - coveralls


