sudo: false
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
cache:
  directories:
  - $HOME/.cache/pip
install:
- pip install -r dev-requirements.txt
script:
- make lint
- make test
after_success:
- make coverage
- coveralls
notifications:
  slack:
    secure: dkLGDo99kuSIZrU6wxBrLp8XNoeYrkgHq95XZ7IMErjmbDyO9HHm2r6IA/Y6gPW2D92l2Q0khtQvMeTR9e+vGfw0gXoPkiZjZXg9suK6k1sFmjwYIh8hmZJNGK/nrVA/E/UI4Fs5nezNldWIT7BPCCAPVXem18nwcFGiyhWOwJvOsN7c611JXT/ZDYrq0MeIbmSveC1tt/cOafHtbVkXbfqXnHB0Hzb3AymaZz0Tq776tabZRgxjqruds/A3myXW3zROP8UNw+TLXSbKuZacGllHVwKEbVru6akD2+H76+aGoOFZROxpYZdqicHFR/x8x/ah38kSbVsZf7tmFlmb6+IkNtBShism34UQV13vVqs/yUgePKyM2QJIQOgt2QlVA3As1hLHxCDSmpPagQIdo89Ti9PiX8NNad9WHouSuZquyNHaaMYwzjG38JNF4tMMUJbJBhnWkzfonEKHPuBR8dRC2TC4s0MH6tIAn3yO9i+pPtBn8JTh5EeCgoZ0RK5wEa16ikiUgrkAJbNJlGUdeQP2tj9IgL2y7jV3WE2bnl9vWNfX1Tvc0Fho9dUoA3iNr2JXxROAljbggrbE39G+hCxqNmB/x0MF9YxMIDrY5bKC/hu9k0XGGEYfEewt5kNsWE7tgokZEn6DT8LPYrP/lXLPhrL4ZIICX+5t4yd5cfE=
deploy:
  provider: pypi
  user: netuitive
  password:
    secure: ER3hJKJcRdzaOBYMqCFEK6NNtiLkwH7kEw5s40VhKaR3kmSLJ+CDVV96jD+HCDQxqjSqva07YnkUTqeF5WGnQrKQLInNhn+PGRLa9WXQBINvrQ6lPHghzzeXzXe/RylkhM3bvzel6bkCjTF+qsLLVRwqDkgJROr6LRP97g2vK3AFJFXD2Ok+RRPpbRkAK0HH0cGZwB7atOqujNCL2/8yLLxC9OJZjX8Rrn4Buw3MK0in0MmV4j5nf1IvnqhrLsWGZ1F/oeOwuN+s6xVbl3c3nyQqi3OvsQqeXZYh0OwNpfKwBfKtcwFM1GMfq/QXYci8VVe1SAxzKCO7zEN80HDcUtQ7qTTrJF9yJtTza2KLG68H1SjMEhoq96nzVATTzK+LufZvpqa2mA5wkXsl63hY+RhGcUc+A+SX6vSKrvK6SWyGwk5OSsJLiG2cgz3jvbly7Ll4cfiojHgrXYNyo5O1htNmibtORdX52oczM3Ag0/eirv8yunmYVnrvlwDYcc/ekE6XdhSv2df6ovgTznXCPi31sbaVHVGRh8q9QY98CjgwzrW8JSfqoc0sCYW6HHWoeP2lJWpX8C7grlx7x3au28wsxAuFITbeveicc8NXfxFXz4jqdX1IEB8wleFtPKmG0L2Lm3zPYOWT96JvOicrxTr2+q/LAa649Cg0X4HeGRI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Netuitive/netuitive-statsd
