sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install -r dev-requirements.txt
script:
- make lint
- make test
after_success:
- make coverage
- coveralls
notifications:
  slack:
    secure: dkLGDo99kuSIZrU6wxBrLp8XNoeYrkgHq95XZ7IMErjmbDyO9HHm2r6IA/Y6gPW2D92l2Q0khtQvMeTR9e+vGfw0gXoPkiZjZXg9suK6k1sFmjwYIh8hmZJNGK/nrVA/E/UI4Fs5nezNldWIT7BPCCAPVXem18nwcFGiyhWOwJvOsN7c611JXT/ZDYrq0MeIbmSveC1tt/cOafHtbVkXbfqXnHB0Hzb3AymaZz0Tq776tabZRgxjqruds/A3myXW3zROP8UNw+TLXSbKuZacGllHVwKEbVru6akD2+H76+aGoOFZROxpYZdqicHFR/x8x/ah38kSbVsZf7tmFlmb6+IkNtBShism34UQV13vVqs/yUgePKyM2QJIQOgt2QlVA3As1hLHxCDSmpPagQIdo89Ti9PiX8NNad9WHouSuZquyNHaaMYwzjG38JNF4tMMUJbJBhnWkzfonEKHPuBR8dRC2TC4s0MH6tIAn3yO9i+pPtBn8JTh5EeCgoZ0RK5wEa16ikiUgrkAJbNJlGUdeQP2tj9IgL2y7jV3WE2bnl9vWNfX1Tvc0Fho9dUoA3iNr2JXxROAljbggrbE39G+hCxqNmB/x0MF9YxMIDrY5bKC/hu9k0XGGEYfEewt5kNsWE7tgokZEn6DT8LPYrP/lXLPhrL4ZIICX+5t4yd5cfE=
deploy:
  provider: pypi
  user: netuitive
  password:
    secure: KW2fT730G/mZ0dxDJ0K7deM4A67aQFo5ma833/GV2h6mddrgIY8MwyF4v3L9F71FqiUC6j+XvcU7GcQ4ClKlY3pgUWr+qi2DWa3kCJsOdBrEgclP7lTnuePj+gGeoq4JGPJq6Mm2OXQwAXVPrHosuW3Q7GNLilumpEFgRGRKr7CgCEuMBJXIUDcAXEFbmil5oIgQo+3YqlDIzmoastvkQzQtsqFeae/0LyMmyIkrFdqCaLKoAxwMsQ8esb95fzNIoz+C3dQ3fEPFijzWXZ34VYuCKSsa3P2dLdj8+kJVl8iIeEX92xU20jKLtNqbF9ZLj+PYMKE0pIINdwccRv0w2xoDPHQ7DSi4CiKGD19ctafJdhtCd3pB0xfMTiZzILr+trRqj9rpam286yvVf4cKUXHceAK8xI+STuGn621OddxIQUlO3p1kGpXsBIH4mfedYvCrADiZT50Gbr5bPnmIFYkdZ1MIjBvdIm3C3UNkQox/tnKQO4Fbr+n5AnXcq7lisUKUkFkznrZzm8cyfbHjpQ5KM3wys8RBjiSkXHP7pYnkuoB+MmQVC/Quq9bfS8j4swKnB+1zRNM3skaGidkaCKqftU6Sq2Ys+hxSy7NTPLFU1pLBKk/WoX/l//OfPteS3b++p/4+qTW+2qVAs2S3ur8g1A+Mc1KmQWdZIHINjio=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Netuitive/netuitive-statsd
